---
# tasks file for roles/cka-ansible
- name: Create the systemgroup
  group:
    name: "{{system_group}}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

- name: Create the systemuser
  user:
    name: "{{system_user}}"
    comment: The systemuser choosed to administrate the kubernetes cluster
    group: "{{system_group}}"
    generate_ssh_key: yes
    ssh_key_file: .ssh/id_rsa
  when: ansible_distribution == 'Debian' or ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: "yes"
    update_cache: yes
    cache_valid_time: 86400
  when: ansible_distribution == 'Debian'

- name: Showing the distribution
  debug:
    var: ansible_distribution
    
- name: Install docker.io
  become: true
  apt:
    name: docker.io
    state: latest
  when: ansible_distribution == 'Debian'
 
- name: Add repository for docker-ce
  copy:
    src: "{{role_path}}/files/docker-ce.repo"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: "root"
    group: "root"
    mode: '0770'
    backup: yes
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'
  
- name: Upgrade all packages
  yum:
    name: '*'
    state: latest
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

- name: Install docker.io
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'Fedora'

- name: Docker systemd cgroups
  file:
    state: directory
    path: "/etc/docker"
    mode: '0755'

- name: Copy docker systemd cgroups config
  copy:
    src: "{{role_path}}/files/daemon.json"
    dest: /etc/docker/daemon.json
    owner: "root"
    group: "root"
    mode: '0770'
    backup: yes
  
- name: Start and enable the docker.service
  become: true
  systemd:
    state: started
    enabled: yes
    name: docker

- name: Check docker.service status
  command: systemctl status docker
  register: result_docker_service
  ignore_errors: yes

- name: Showing the report
  debug:
    var: result_docker_service

# Debian specific actions
- name: Add apt-key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_distribution == 'Debian'

- name: Add Software Repositories
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
  when: ansible_distribution == 'Debian'

- name: Package installation
  apt:
    pkg:
    - kubeadm
    - kubelet
    - kubectl
  when: ansible_distribution == 'Debian'

# Redhat specific actions
- name: Add repository for Kubernetes
  yum_repository:
    name: kubernetes
    description: Kubernetes YUM repo
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
  when: ansible_distribution == 'RedHat'

- name: Package installation
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - kubernetes-kubeadm
    - kubernetes-node
    - kubernetes-client
  when: ansible_distribution == 'Fedora'

- name: Enable kubelet
  become: yes
  shell: |
    systemctl enable --now kubelet

- name: Disable SWAP
  become: yes
  shell: |
    swapoff -a 

- name: Disable SWAP in fstab
  become: yes
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Set system hostname
  hostname:
    name: "{{inventory_hostname}}"

- name: kubelet version
  shell: |
    kubelet --version | awk '{ print $2 }'
  register: kubelet_version
  when: "inventory_hostname in groups['master']"
 
- name: Showing the kubelet_version
  debug:
    var: kubelet_version

- name: Adding the kubeadm-config
  template:
    src: "{{role_path}}/files/kubeadm-config.yaml.j2"
    dest: /tmp/kubeadm-config.yaml
    owner: "{{system_user}}"
    group: "{{system_group}}"
    mode: '0770'
  when: "inventory_hostname in groups['master']"

#- name: Copy the kubeadm-config
#  copy:
#  src: "{{role_path}}/files/kubeadm-config.yaml"
#    dest: /tmp/kubeadm-config.yaml
#    owner: "{{system_user}}"
#    group: "{{system_group}}"
#    mode: '0770'
#    backup: yes

- name: Initialize the cluster
  shell: |
    kubeadm init --config /tmp/kubeadm-config.yaml >> /var/log/kubeadm_init.log
  when: "inventory_hostname in groups['master']"

- name: Add the kube directory to the "{{system_user}}"
  file:
    state: directory
    path: "/home/{{system_user}}/.kube"
    mode: '0755'
  when: "inventory_hostname in groups['master']"

- name: Add the configuration
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{system_user}}/.kube"
    owner: "{{system_user}}"
    group: "{{system_group}}"
    mode: '0770'
    remote_src: yes
  when: "inventory_hostname in groups['master']"
   
- name: Copy Pod Network config
  copy:
    src: "{{role_path}}/files/kube-flannel.yml"
    dest: /tmp/kube-flannel.yml
    owner: "{{system_user}}"
    group: "{{system_group}}"
    mode: '0770'
    backup: yes
  when: "inventory_hostname in groups['master']"
 
- name: Deploy Pod Network to cluster
  become: yes
  shell: |
    kubectl apply -f /tmp/kube-flannel.yml
  when: "inventory_hostname in groups['master']"

- name: Join command retrieved from the master node
  shell: |
    tail -n 2 /var/log/kubeadm_init.log
  register: kube_register
  when: "inventory_hostname in groups['master']"

- name: Check the join command retrieved from master node
  debug:
    var: kube_register
  when: "inventory_hostname in groups['master']"

- name: Join worker node to cluster
  shell: |
    "{{kube_register}}"
  when: "inventory_hostname in groups['node']"

- name: Check all the nodes
  shell: |
    kubectl get nodes
  when: "inventory_hostname in groups['node']"


